import type {
  InteractionMode,
  ModeContext,
  SystemOutput,
  ModeCapabilities,
} from '../types';

const BOND_GATE_LEVEL = 7;

export interface JournalEntryData {
  date: string;
  content: string;
  mood: string;
  milestone?: string;
}

export class JournalMode implements InteractionMode {
  readonly type = 'journal' as const;
  readonly displayName = 'Journal';
  readonly surface = 'dom' as const;
  readonly tier = 'review' as const;

  private ctx: ModeContext | null = null;
  private indicator: HTMLDivElement | null = null;
  private entries: JournalEntryData[] = [];

  mount(context: ModeContext): void {
    this.ctx = context;
    const bondLevel = (context.config?.bondLevel as number) ?? 0;

    if (context.overlayContainer) {
      this.indicator = document.createElement('div');
      this.indicator.className = 'journal-indicator';

      if (bondLevel >= BOND_GATE_LEVEL) {
        this.indicator.textContent = '📓 Journal';
        this.indicator.style.cssText = [
          'position: absolute',
          'pointer-events: auto',
          'cursor: pointer',
          'font-size: 13px',
          'background: rgba(200, 220, 255, 0.85)',
          'color: #2a4a7f',
          'padding: 4px 10px',
          'border-radius: 6px',
        ].join(';');
      } else {
        this.indicator.textContent = `Reach Bond Lv.${BOND_GATE_LEVEL} to unlock Journal`;
        this.indicator.style.cssText = [
          'position: absolute',
          'pointer-events: none',
          'font-size: 12px',
          'color: rgba(150, 150, 150, 0.8)',
          'background: rgba(80, 80, 80, 0.1)',
          'padding: 4px 8px',
          'border-radius: 6px',
        ].join(';');
      }

      const pos = context.getPetPosition();
      this.indicator.style.left = `${pos.x + pos.width + 10}px`;
      this.indicator.style.bottom = `${window.innerHeight - pos.y + 20}px`;

      context.overlayContainer.appendChild(this.indicator);
    }
  }

  unmount(): void {
    this.indicator?.remove();
    this.indicator = null;
    this.ctx = null;
  }

  handleOutput(_output: SystemOutput): void {
    // Journal mode doesn't react to real-time outputs
    // Entries are generated by the backend scheduler at end-of-day
  }

  capabilities(): ModeCapabilities {
    return {
      displaysText: true,
      acceptsTextInput: false,
      displaysChoices: false,
      triggersCareActions: false,
      requiresWebview: true,
      allowsConcurrent: false,
      supportsMultiAgent: false,
    };
  }

  getEntryCount(): number {
    return this.entries.length;
  }

  getEntries(): JournalEntryData[] {
    return [...this.entries];
  }

  getEntriesByRange(start: string, end: string): JournalEntryData[] {
    return this.entries.filter(e => e.date >= start && e.date <= end);
  }

  addEntry(date: string, content: string, mood: string, milestone?: string): void {
    const bondLevel = (this.ctx?.config?.bondLevel as number) ?? 0;
    if (bondLevel < BOND_GATE_LEVEL) return;

    this.entries.push({ date, content, mood, milestone });
  }

  clearEntries(): void {
    this.entries = [];
  }
}
